apiVersion: v1
kind: Secret
metadata:
  name: {{ template "oracle-proxy.fullname" . }}
  labels:
      app: {{ template "oracle-proxy.fullname" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.db_password | b64enc }}
